version: "3"

services:
  firefox:
    image: selenium/standalone-firefox-debug:3.14.0-curium

    expose:
      - 4444

    volumes:
      - "/dev/shm:/dev/shm"

    networks:
      - selenium

  web_app:
    dns:
      - 8.8.8.8
    build: .
    command: python -u -m web_app

    ports:
      - 127.0.0.1:8080:8080

    environment:
      - SELENIUM=http://firefox:4444/wd/hub

    networks:
      - selenium
    depends_on:
      - firefox

volumes:
  devshm:

networks:
  selenium: